Polarion script: add tests
RedHatQE/python-utility-scripts pull request #27
Opened 2024-04-04 12:53 UTC by myakove

2024-04-04 12:53 UTC, redhat-qe-bot2 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-04-04 13:03 UTC, rnetser approved these changes

2024-04-04 13:05 UTC, rnetser approved these changes

2024-04-04 13:24 UTC, dbasunag requested changes

2024-04-04 13:24 UTC, dbasunag commented on tests/polarion/test_verify_polarion_requirements.py
> +def test_missing_project_id():
This two does not test the actual functions.

2024-04-04 13:31 UTC, myakove commented on tests/polarion/test_verify_polarion_requirements.py
> +def test_missing_project_id():
Well, you can't test the actual functions since all the logic reside in `validate_polarion_requirements` and this function use `pylero`.
`pylero` work in a way that once you import it, the code will try to create a connection to Polarion instance (and we don't have one).

Your previous code was mocked `validate_polarion_requirements`, meaning that you didn't test this function at all.

I prefer not to write test when the alternative is to write test that check nothing.

2024-04-04 14:45 UTC, dbasunag commented on tests/polarion/test_verify_polarion_requirements.py
> +def test_missing_project_id():
mocking allows us to play with the values and ensure the returned values are appropriately handled, no? Otherwise, we are just adding tests that basically is doing basic cli validations, while the code internally could be totally broken.

2024-04-05 21:45 UTC, myakove commented on tests/polarion/test_verify_polarion_requirements.py
> +def test_missing_project_id():
no, if you mock your own code you do not test it.

2024-04-08 10:55 UTC, dbasunag commented on tests/polarion/test_verify_polarion_requirements.py
> +def test_missing_project_id():
Then we should mock it at the right place - e.g. mocking the polarion calls. I will work on adjusting the code and see what can be done.

2024-04-08 16:39 UTC, dbasunag approved these changes

2024-04-08 18:04 UTC, myakove commented
/verified

2024-04-08 18:04 UTC, merged