base PR for set polarion as automated
RedHatQE/python-utility-scripts pull request #30
Opened 2024-04-08 19:42 UTC by dbasunag

2024-04-08 22:41 UTC, dbasunag commented
/verified

2024-04-09 08:17 UTC, myakove requested changes

2024-04-09 08:17 UTC, myakove commented on apps/polarion/polarion_utils.py
> +APPROVED = "approved"
Duplicate code.

2024-04-09 08:17 UTC, myakove commented on apps/polarion/polarion_utils.py
> +    polarion_test_ids=None,
```suggestion
    polarion_test_ids=None,
```
Why this is None?
The function do nothing if this is None

2024-04-09 08:17 UTC, myakove commented on pyproject.toml
> +pyutils-polarion_set_automated = "apps.polarion.polarion_set_automated:polarion_approve_automate"
should be `-`

2024-04-09 08:17 UTC, myakove commented on tests/polarion/test_verify_polarion_requirements.py
> +BASE_COMMAND = "poetry run python3 apps/polarion/polarion_verify_tc_requirements.py"
why `python3`?

2024-04-09 08:17 UTC, myakove commented on tests/polarion/test_polarion_automated.py
> +    assert rc
already tested.

2024-04-09 11:58 UTC, dbasunag commented on tests/polarion/test_verify_polarion_requirements.py
> +BASE_COMMAND = "poetry run python3 apps/polarion/polarion_verify_tc_requirements.py"
This is not needed, I will undo.

2024-04-09 11:59 UTC, dbasunag commented on tests/polarion/test_polarion_automated.py
> +    assert rc
base command is different though.

2024-04-09 12:03 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +APPROVED = "approved"
Removed.

2024-04-09 12:17 UTC, myakove commented on tests/polarion/test_polarion_automated.py
> +    assert rc
this do not test anything (beside click), the uderline commands already tested.

2024-04-09 13:03 UTC, dbasunag commented on tests/polarion/test_polarion_automated.py
> +    assert rc
Ok, then I can remove it.

2024-04-09 13:08 UTC, dbasunag commented
/verified

2024-04-22 13:32 UTC, dbasunag commented
/verified

2024-04-22 19:54 UTC, dbasunag commented
/verified

2024-04-24 11:49 UTC, merged