base PR for set polarion as automated""
RedHatQE/python-utility-scripts pull request #36
Opened 2024-04-24 12:38 UTC by dbasunag

Reverts RedHatQE/python-utility-scripts#34

2024-04-24 12:38 UTC, msi-b1 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-04-24 13:00 UTC, rnetser commented on apps/polarion/polarion_set_automated.py
> +        raise click.Abort()
please convert `click.Abort()` to custom exceptions.

2024-04-24 13:04 UTC, rnetser requested changes

2024-04-24 13:04 UTC, rnetser commented on apps/polarion/polarion_set_automated.py
> +        LOGGER.setLevel(logging.DEBUG)
```suggestion
    if not verbose:
        logging.disable(logging.CRITICAL)
```

and then you do not need debug

2024-04-24 13:28 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +def get_polarion_project_id(project_id, config_file_path, util_name):
Util name is required param. But the other two would be set to None as either of those can be passed.

2024-04-24 14:22 UTC, dbasunag commented on apps/polarion/polarion_set_automated.py
> +def polarion_approve_automate(config_file_path, project_id, verbosity):
Creating a separate PR for this one.

2024-04-24 15:17 UTC, dbasunag commented on apps/polarion/polarion_set_automated.py
> +    if verbosity:
I am not clear on this one. These won't need ipdb/pdb for debugging failures. If they fail, it is due to polarion connectivity or not being able to access/update polarions. So even with function_runner_with_pdb(), I would need to pass `--pdb` to default to false. I don't see a benefit of using it here. Please advice.

2024-05-03 01:13 UTC, dbasunag commented on apps/polarion/polarion_set_automated.py
> +    if verbosity:
Kept this as per chat.

2024-05-03 01:15 UTC, dbasunag commented
@myakove / @rnetser I had to change the coverage fail_under percentage. With polarion not being tested that well, current coverage  67.51% won't meet 75% threshold, may be in future it can be improved for other areas. Please let me know what you think.

2024-05-04 22:30 UTC, dbasunag commented
/verified

2024-05-05 05:58 UTC, myakove requested changes

2024-05-05 05:58 UTC, myakove commented on apps/polarion/polarion_set_automated.py
> +        logging.disable(logging.WARNING)
you should use logger info and not debug in all your logs and here you should enable logs if verbose else disable all logs.

2024-05-05 05:58 UTC, myakove commented on apps/polarion/polarion_utils.py
> +        raise click.Abort()
click.Abort() exception is bad exception, please create your own exception that can have msg.

2024-05-13 14:24 UTC, dbasunag commented on apps/polarion/polarion_set_automated.py
> +def approve_tests(polarion_project_id: str, added_ids: Iterable[str]) -> Dict[str, List[str]]:
mypy did not like it originally, so I had to change it to Iterable. But it has been a while, so I will retry and let you know.

2024-05-13 21:51 UTC, dbasunag commented on apps/polarion/polarion_set_automated.py
> +def approve_tests(polarion_project_id: str, added_ids: Iterable[str]) -> Dict[str, List[str]]:
Updated.

2024-05-13 22:22 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +        raise click.Abort()
Replaced with exceptions.

2024-05-13 22:23 UTC, dbasunag commented on apps/polarion/polarion_set_automated.py
> +        logging.disable(logging.WARNING)
Ok, please let me know if the changes I made is aligned to what you want.

2024-05-13 22:23 UTC, dbasunag commented on apps/polarion/polarion_set_automated.py
> +        logging.disable(logging.WARNING)
I left `logging.disable(logging.ERROR)` as otherwise there would be no debugging on failure.

2024-05-15 17:30 UTC, dbasunag commented
/verified

2024-05-16 11:44 UTC, dbasunag commented
/verified

2024-05-23 12:46 UTC, rnetser approved these changes

2024-05-23 12:48 UTC, dbasunag commented
/verified

2024-05-23 12:48 UTC, merged

2024-05-23 12:48 UTC, redhat-qe-bot1 commented
Pull request already merged, not running verified