add mypy and update files
RedHatQE/python-utility-scripts pull request #38
Opened 2024-04-24 20:33 UTC by dbasunag

2024-04-24 20:33 UTC, msi-b1 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-04-25 05:57 UTC, rnetser requested changes

2024-04-25 05:57 UTC, rnetser commented on apps/polarion/polarion_utils.py
> +    return data.decode("utf-8")
`utf-8` is the default; can be removed

2024-04-25 05:57 UTC, rnetser commented on apps/polarion/polarion_utils.py
> +def git_diff_lines() -> dict:
```suggestion
def git_diff_lines() -> Dict:
```

2024-04-25 05:57 UTC, rnetser commented on apps/polarion/polarion_utils.py
> +    polarion_test_ids: list,
```suggestion
    polarion_test_ids: List,
```

2024-04-25 05:57 UTC, rnetser commented on apps/polarion/polarion_utils.py
>      tests_with_missing_requirements = []
```suggestion
    tests_with_missing_requirements : List = []
```

2024-04-25 05:57 UTC, rnetser commented on apps/polarion/polarion_utils.py
>      tests_with_missing_requirements = []
typing is missing in some definitions

2024-04-25 05:57 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +def has_verify(config_file_path: Any, project_id: str, verbosity: bool) -> Any:
why `config_file_path` is `Any`?

2024-04-25 05:57 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +def has_verify(config_file_path: Any, project_id: str, verbosity: bool) -> Any:
why `-> Any`, the function does not return anything

2024-04-25 05:57 UTC, rnetser commented on apps/unused_code/unused_code.py
> +    def is_func(_elm: Any) -> Any:
why Any? please fix in all places. this function returns bool

2024-04-25 07:28 UTC, merged