Initial commit to add Unused code check script
RedHatQE/python-utility-scripts pull request #4
Opened 2024-01-25 14:46 UTC by dbasunag

2024-01-25 14:51 UTC, dbasunag commented
/verified

2024-01-29 09:31 UTC, myakove requested changes

2024-01-29 09:31 UTC, myakove commented on README.md
> +poetry run unusedcode
please add that this should run from inside the git repository folder.

2024-01-29 09:31 UTC, myakove commented on README.md
> +# unusedcode
`Usage` of `unusedcode` should be under `unusedcode` section

I think:
```
# Scripts
## unusedcode
### Usage
....
....
## another script
```

2024-01-29 09:31 UTC, myakove commented on README.md
> +poetry run unusedcode
and will work only for test repository using ptest

2024-01-29 09:31 UTC, myakove commented on app/unused_code/unused_code.py
> +        if os.path.basename(py_file) == "pytest_matrix_utils.py":
`"pytest_matrix_utils.py"` should be passed from the user (config file???)

2024-01-29 09:31 UTC, myakove commented on app/utils.py
> +    LOGGER.info(repo_location)
Either remove this log or make it meaningful

2024-01-29 10:04 UTC, rnetser requested changes

2024-01-29 10:04 UTC, rnetser commented on app/utils.py
> +def all_python_files(repo_location):
please set `repo_location` with default value of current dir

2024-01-29 10:04 UTC, rnetser commented on pyproject.toml
> +
consider adding development packages - ipython and ipdb

2024-01-29 15:34 UTC, dbasunag commented on README.md
> +# python-utility-scripts
Yeah. I will add the installation information.

2024-01-29 15:35 UTC, dbasunag commented on app/utils.py
> +def all_python_files(repo_location):
Since this would be running from the repo location, I will remove the argument.

2024-01-29 15:37 UTC, dbasunag commented on pyproject.toml
> +
ipython needs ">=3.10,<4.0, so skipping that (I want to use ^3.8), but adding ipdb

2024-01-29 15:39 UTC, dbasunag commented on app/unused_code/unused_code.py
> +    for py_file in all_python_files("."):
Done. But removed the argument from this call, as it is no longer relevant.

2024-01-29 16:20 UTC, dbasunag commented on app/unused_code/unused_code.py
> +import ast
renamed it to utility_scripts.

2024-01-29 18:52 UTC, dbasunag commented
/verified

2024-01-29 18:53 UTC, dbasunag commented on README.md
> +poetry run unusedcode
Done.

2024-01-29 19:04 UTC, dbasunag commented
/verified

2024-01-29 20:17 UTC, dbasunag commented on README.md
> +poetry run unusedcode
I have added installation step. Please let me know if this works.

2024-01-30 09:17 UTC, myakove requested changes

2024-01-30 09:17 UTC, myakove commented on README.md
> +# python-utility-scripts
you missing more than installation information for this to be released.

2024-01-30 09:17 UTC, myakove commented on README.md
> +poetry add python-utility-scripts
if release, this should be `pip3 install python-utility-scripts`

2024-01-30 09:17 UTC, myakove commented on README.md
> +e.g to skip running unsedcode check on file pytest_matrix_utils.py, following can be added to `<repo_path>/.config/unusedcode/config`
this should be under user home and you should have one config for all your scripts.
`~/.config/python-utility-scripts/config.yaml`

2024-01-30 09:17 UTC, myakove commented on README.md
> +e.g to skip running unsedcode check on file pytest_matrix_utils.py, following can be added to `<repo_path>/.config/unusedcode/config`
and you should except user args from cli for it as well

2024-01-30 09:17 UTC, myakove commented on README.md
> +pytest_matrix_utils.py
rename to `my_exclude_file.py` please

2024-01-30 09:17 UTC, myakove commented on pyproject.toml
> +
add `ipython = "*"`, it should work

2024-01-30 09:20 UTC, myakove requested changes

2024-01-30 09:20 UTC, myakove commented on README.md
> +# python-utility-scripts
add 
```
[tool.poetry-dynamic-versioning.substitution]
files = ["VERSION"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
```

to `pyproject.toml` file.
create new file `VERSION` and add `0.0.0` to it.

2024-01-30 09:43 UTC, rnetser requested changes

2024-01-30 09:43 UTC, rnetser commented on .github/in-solidarity.yml
> + - "utility_scripts/manifests/install-config-template.j2"
not relevant

2024-01-30 09:43 UTC, rnetser commented on README.md
> +poetry run unusedcode
I meant for developer in this repo

2024-01-30 09:43 UTC, rnetser commented on pyproject.toml
> +
ipython and ipdb should be under `[tool.poetry.dev-dependencies]`

2024-01-30 09:43 UTC, rnetser commented on utility_scripts/unused_code/unused_code.py
> +    # check if any config file with a list of files to skip checking exists:
please use proper docstring

2024-01-30 09:43 UTC, rnetser commented on utility_scripts/unused_code/unused_code.py
> +            list_to_skip = [line.rstrip() for line in _file]
```suggestion
           return [line.rstrip() for line in _file]
```

2024-01-30 12:49 UTC, dbasunag commented on README.md
> +# python-utility-scripts
ok, I will see some of your repos and add to the files accordingly.

2024-01-30 13:23 UTC, dbasunag commented on .github/in-solidarity.yml
> + - "utility_scripts/manifests/install-config-template.j2"
Did not notice this before. Thank you.

2024-01-30 18:14 UTC, dbasunag commented on README.md
> +poetry run unusedcode
Done.

2024-01-30 18:15 UTC, dbasunag commented on pyproject.toml
> +version = "0.0.1"
@myakove should this be removed, since you asked me to add VERSION file?

2024-01-31 06:20 UTC, rnetser requested changes

2024-01-31 06:20 UTC, rnetser commented on README.md
> +#### Usage
this should be under local run

2024-01-31 06:20 UTC, rnetser commented on README.md
> +To skip unused code check on specific files of a repository, a config file with the list of names of such files, separated by `\n` should be added to
why not add a section for skipped files and have it as a list?

2024-01-31 06:20 UTC, rnetser commented on README.md
> +#### Config file
i think it will be nice to have a separate readme for each script

2024-01-31 06:20 UTC, rnetser commented on README.md
> +```
this is not bash command

2024-01-31 06:20 UTC, rnetser commented on README.md
> +```bash
please add newline before each command section (e.g before ```bash)

2024-01-31 06:20 UTC, rnetser commented on pyproject.toml
> +
`repository` is missing

2024-01-31 06:20 UTC, rnetser commented on utility_scripts/utils.py
> +    for root, _, files in os.walk(os.path.abspath(os.curdir)):
why remove the option to get python dir from the user?

2024-01-31 08:33 UTC, myakove requested changes

2024-01-31 08:33 UTC, myakove commented on README.md
> +#### Config file
+1

2024-01-31 08:33 UTC, myakove commented on README.md
> +To skip unused code check on specific files of a repository, a config file with the list of names of such files, separated by `\n` should be added to
I think we should support exclude and include lists.
this way it can be useful for any project not just for testing, for example in non testing project I can set mu `utils` folder in the include list (the code needs to be change to support non pytest projects)

2024-01-31 08:33 UTC, myakove commented on pyproject.toml
> +version = "0.0.1"
No, poetry will fail if not version, this can be set to `0.0.0`

2024-01-31 08:33 UTC, myakove commented on pyproject.toml
> +unusedcode = "utility_scripts.unused_code.unused_code:get_unused_functions"
we need to think of a better name for this, we need some relation in the name to the repo

2024-01-31 08:33 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +@click.option("--config-file-path", "-c", help="Provide absolute path to the config file")
each option in config file should be also supported via the cli

2024-01-31 08:33 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +    func_ignore_prefix = ["pytest_"]
should be in config, cli arg

2024-01-31 08:33 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +            LOGGER.warning(f"File {py_file} is being skipped, as indicated in config file")
`as indicated in config file` not needed, please remove

2024-01-31 12:52 UTC, dbasunag commented on README.md
> +To skip unused code check on specific files of a repository, a config file with the list of names of such files, separated by `\n` should be added to
Can this be done in future?

2024-01-31 12:52 UTC, dbasunag commented on README.md
> +#### Config file
Should each Readme be under script locations?

2024-01-31 12:55 UTC, dbasunag commented on utility_scripts/unused_code/unused_code.py
> +@click.option("--config-file-path", "-c", help="Provide absolute path to the config file")
Currently there is no option in the config file, expectation is user would pass a list of exclude files in it. Include list is not supported. May be support it in future? What do you say?

2024-01-31 12:56 UTC, dbasunag commented on utility_scripts/unused_code/unused_code.py
> +    func_ignore_prefix = ["pytest_"]
Ok, I will add it.

2024-01-31 13:20 UTC, dbasunag commented on README.md
> +#### Usage
The whole script section should be under `Local run`?

2024-01-31 13:20 UTC, dbasunag commented on README.md
> +To skip unused code check on specific files of a repository, a config file with the list of names of such files, separated by `\n` should be added to
I need to expand this one, as now even functions can be passed as a list or via config file

2024-01-31 19:06 UTC, dbasunag commented on pyproject.toml
> +unusedcode = "utility_scripts.unused_code.unused_code:get_unused_functions"
Changed to pyutils-unusedcode

2024-01-31 19:06 UTC, dbasunag commented on README.md
> +#### Config file
Added a readme for the script.

2024-01-31 19:07 UTC, dbasunag commented on README.md
> +To skip unused code check on specific files of a repository, a config file with the list of names of such files, separated by `\n` should be added to
include list would be handled in a separate PR

2024-01-31 19:07 UTC, dbasunag commented on README.md
> +#### Usage
Usage moved to the script readme, with pointers to the readme.

2024-02-01 08:21 UTC, myakove requested changes

2024-02-01 08:21 UTC, myakove commented on README.md
> +* [pyutils-unusedcode](https://github.com/RedHatQE/python-utility-scripts/unused_code/README.md)
there is already a python module called `pyutils`, can be confusing.
maybe `pyappsutils`?

2024-02-01 08:21 UTC, myakove commented on README.md
> +`~/.config/python-utility-scripts/config.yaml`. Script specific config section details can be found in associated script README.md
Now that I think of that, we have our own folder for config `~/.config/python-utility-scripts` so we can have config for each script under it.
`unusedcode-config.yaml` for example.

2024-02-01 08:21 UTC, myakove commented on pyproject.toml
> +
Missing 

homepage = "https://github.com/RedHatQE/python-utility-scripts"
documentation = "https://github.com/RedHatQE/python-utility-scripts/blob/main/README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

2024-02-01 08:21 UTC, myakove commented on pyproject.toml
> +    { include = "utility_scripts" },
`utility_scripts`can be renamed to `scripts` or `apps`

2024-02-01 08:21 UTC, myakove commented on utility_scripts/click_list_type.py
> +class ListParamType(click.ParamType):
@rnetser we may want to use this one in our repositories once this is merged

2024-02-01 08:21 UTC, myakove commented on utility_scripts/unused_code/README.md
> +poetry run pyutils pyutils-unusedcode
`poetry run` only needed for local run, this tool used after installing from Pypi so it should be only `pyutils-unusedcode`

2024-02-01 08:21 UTC, myakove commented on utility_scripts/unused_code/README.md
> +poetry run pyutils pyutils-unusedcode --config-file-path <absolute_path_to_config_yaml>
No need to describe every cli arg, you have --help for that.
Mention here that --help exists

2024-02-01 08:21 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +    if os.path.exists(skip_config_file):
if `config_file_path` you need to raise if nt exists (`config_file_path` means that the user pass the config from the cli and we expected to be exists.
)

2024-02-01 08:21 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +    type=click.Path(),
Use click `default` to set the default path.

2024-02-01 08:21 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +    "--exclude-file-list", default=None, help="Provide a comma-separated list of files to exclude", type=ListParamType()
no need to set `default=None` which is the default.

2024-02-01 08:21 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +def get_exclude_list_from_config_file(config_file_path):
this is not excluded list, it's the all config (which now contains only exclude), please rename.

2024-02-01 08:21 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +    func_ignore_prefix = skip_config.get("exclude_function_prefix") or exclude_function_prefixes
I think CLI arg should override any arg from config.
`exclude_function_prefixes or skip_config.get("exclude_function_prefix") or []`

2024-02-01 08:21 UTC, myakove commented on utility_scripts/utils.py
> +    for root, _, files in os.walk(os.path.abspath(os.curdir)):
I don;t understand how run from the repository location related to this.

Anyway I think we can force some static exclude_dirs like the list we have here.

2024-02-01 08:21 UTC, myakove commented on utility_scripts/unused_code/unused_code.py
> +        sys.exit(1)
Use click.Abort

2024-02-01 12:18 UTC, dbasunag commented on pyproject.toml
> +    { include = "utility_scripts" },
@rnetser asked me to rename from apps. `scripts` did not work.

2024-02-01 12:36 UTC, dbasunag commented on utility_scripts/utils.py
> +    for root, _, files in os.walk(os.path.abspath(os.curdir)):
If we are running from the root directory and by default we want to check every code in the repository, then making this an argument does not make any sense. But once we add support for include_dir options this would definitely change.

2024-02-01 12:39 UTC, dbasunag commented on README.md
> +* [pyutils-unusedcode](https://github.com/RedHatQE/python-utility-scripts/unused_code/README.md)
Done.

2024-02-01 12:41 UTC, dbasunag commented on pyproject.toml
> +    { include = "utility_scripts" },
Renamed to `apps`

2024-02-01 15:21 UTC, dbasunag commented on utility_scripts/unused_code/unused_code.py
> +        sys.exit(1)
Done.

2024-02-01 15:28 UTC, dbasunag commented on utility_scripts/unused_code/README.md
> +poetry run pyutils pyutils-unusedcode
updated

2024-02-01 15:29 UTC, dbasunag commented on utility_scripts/unused_code/unused_code.py
> +    if os.path.exists(skip_config_file):
I missed that.

2024-02-01 15:31 UTC, dbasunag commented on utility_scripts/unused_code/unused_code.py
> +    type=click.Path(),
I decided against default, because it is possible for the user to not to have a exclude/include list. In that case they would need to have a empty config, for no reason. But will update the help text.

2024-02-01 15:32 UTC, dbasunag commented on utility_scripts/unused_code/unused_code.py
> +    func_ignore_prefix = skip_config.get("exclude_function_prefix") or exclude_function_prefixes
Updated

2024-02-01 15:35 UTC, dbasunag commented on README.md
> +`~/.config/python-utility-scripts/config.yaml`. Script specific config section details can be found in associated script README.md
For now we have one script, so we can finalize the design of the config file once we have more. Wdyt?

2024-02-01 18:52 UTC, dbasunag commented on README.md
> +`~/.config/python-utility-scripts/config.yaml`. Script specific config section details can be found in associated script README.md
Depending upon how many ends up in this repository, it could be a pain point for the users. I prefer 1 config like you suggested before.

2024-02-04 08:37 UTC, myakove requested changes

2024-02-04 08:37 UTC, myakove commented on README.md
> +pip3 install python-utility-scripts
```suggestion
pip3 install python-utility-scripts --user
```

2024-02-04 08:37 UTC, myakove commented on README.md
> +* [pyappsutils-unusedcode](https://github.com/RedHatQE/python-utility-scripts/blob/main/README.md)
Please move under `Repository for various python utility scripts` as bullets.

2024-02-04 08:37 UTC, myakove commented on apps/click_list_type.py
> +# Reference: https://gist.github.com/welel/9cf860dd3f4d3e09f9b4305878b3a04e
Please move to utils.py

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +urllib3.disable_warnings()
I think this is not needed anymore.

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +    type=click.Path(),
click.Path(exists=True)

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +    if config_file_path and not os.path.exists(config_file_path):
Not needed, click can check it for you

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +    skip_config_file = config_file_path or os.path.join(
rename `skip_config_file` to something else, this is not just config for skip

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +    unused_code = config_yaml.get("pyappsutils-unusedcode", {})
please rename ot `unused_code_config`

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/README.md
> +This would exclude any functions with prefix my_exclude_function_prefix and file my_exclude_file.py from unused code check
please add example how to run from cli with excludes

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +@click.option("--exclude-file-list", help="Provide a comma-separated list of files to exclude", type=ListParamType())
```suggestion
@click.option("--exclude-files", help="Provide a comma-separated string of files to exclude", type=ListParamType())
```

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +    help="Provide a comma-separated list of function prefixes to exclude",
```suggestion
    help="Provide a comma-separated string of function prefixes to exclude",
```

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +    func_ignore_prefix = exclude_function_prefixes or unused_code.get("exclude_function_prefix") or []
```suggestion
    func_ignore_prefix = exclude_function_prefixes or unused_code.get("exclude_function_prefix", [])
```

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +    file_ignore_list = exclude_file_list or unused_code.get("exclude_files") or []
ditto

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +        LOGGER.info(f"Checking file: {py_file}")
Please move this logger after the skip file, no need to log the same file twice.

2024-02-04 08:37 UTC, myakove commented on apps/unused_code/unused_code.py
> +            ignore_functions = (
Can you extract ignore_functions to function?

2024-02-05 12:53 UTC, rnetser requested changes

2024-02-05 12:53 UTC, rnetser commented on apps/utils.py
> +class ListParamType(click.ParamType):
please ref to the code source

2024-02-05 13:17 UTC, dbasunag commented on apps/utils.py
> +class ListParamType(click.ParamType):
Done.

2024-02-05 13:17 UTC, dbasunag commented on apps/click_list_type.py
> +# Reference: https://gist.github.com/welel/9cf860dd3f4d3e09f9b4305878b3a04e
Done

2024-02-05 13:21 UTC, dbasunag commented
\verified

2024-02-05 15:30 UTC, dbasunag commented
/verified

2024-02-05 20:25 UTC, dbasunag commented
/verified

2024-02-06 00:43 UTC, dbasunag commented
/verify

2024-02-06 00:44 UTC, dbasunag commented
/verified

2024-02-06 12:40 UTC, myakove requested changes

2024-02-06 12:40 UTC, myakove commented on apps/unused_code/README.md
> +pyappsutils-unusedcode --exclude-function-prefixes '["my_exclude_function1","my_exclude_function2"]'
`'["my_exclude_function1","my_exclude_function2"]'` this will not work

2024-02-06 12:40 UTC, myakove commented on apps/unused_code/unused_code.py
> +    )
should be added to click option as default.

2024-02-06 12:40 UTC, myakove commented on apps/unused_code/unused_code.py
> +        if file_ignore_list and os.path.basename(py_file) in file_ignore_list:
I think `if file_ignore_list` can be removed, you can check if `os.path.basename(py_file) in file_ignore_list`

on empty list it will return False

2024-02-06 12:40 UTC, myakove commented on apps/unused_code/unused_code.py
> +def get_ignore_function_list(ignore_prefix_list, function):
this should be return bool, not list.
and should be renamed.

2024-02-06 12:40 UTC, myakove commented on apps/unused_code/unused_code.py
> +        LOGGER.error(message)
why do we need `LOGGER` and `click.echo`?

2024-02-06 12:40 UTC, myakove commented on tests/test_unused_code.py
> +    runner = CliRunner()
should be extract to function, duplicate code.

2024-02-06 12:40 UTC, myakove commented on tests/test_unused_code.py
> +def test_unused_code_function_list_exclude():
what about positive test?

2024-02-06 12:40 UTC, myakove commented on tests/test_unused_code.py
> +from simple_logger.logger import get_logger
files should be under `tests/unused_code/` folder

2024-02-06 12:40 UTC, myakove commented on tox.ini
> +    pre-commit
not needed, will be called on `git commit` and run as check on each PR

2024-02-06 12:40 UTC, myakove commented on tox.ini
> +    pytest
`pytest` should be add to poetry under tests section

2024-02-06 13:03 UTC, dbasunag commented on apps/unused_code/README.md
> +pyappsutils-unusedcode --exclude-function-prefixes '["my_exclude_function1","my_exclude_function2"]'
This currently is working.

2024-02-06 13:19 UTC, dbasunag commented on tests/test_unused_code.py
> +def test_unused_code_function_list_exclude():
test_unused_code_function_list_exclude_all and test_unused_code_file_list are positive tests.

2024-02-06 13:22 UTC, dbasunag commented on apps/unused_code/unused_code.py
> +        LOGGER.error(message)
click.echo is needed for the unittests to scrape though the output, I will remove LOGGER (it just makes it pop up)

2024-02-06 14:04 UTC, dbasunag commented on tox.ini
> +    pre-commit
ok, removing pre-commit from tox

2024-02-06 17:39 UTC, dbasunag commented
/verified

2024-02-12 08:51 UTC, myakove requested changes

2024-02-12 08:51 UTC, myakove commented on apps/unused_code/README.md
> +pyappsutils-unusedcode --exclude-function-prefixes '["my_exclude_function1","my_exclude_function2"]'
[] are not needed here.

2024-02-12 11:54 UTC, dbasunag commented on apps/unused_code/README.md
> +pyappsutils-unusedcode --exclude-function-prefixes '["my_exclude_function1","my_exclude_function2"]'
Done

2024-02-12 11:54 UTC, dbasunag commented
/verified

2024-02-13 12:48 UTC, dbasunag commented
/verified

2024-02-13 13:41 UTC, myakove approved these changes

2024-02-13 13:44 UTC, merged