Add polarion test requirement verification script
RedHatQE/python-utility-scripts pull request #6
Opened 2024-01-25 21:58 UTC by dbasunag

2024-01-25 21:58 UTC, redhat-qe-bot1 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-01-25 22:35 UTC, dbasunag commented
/wip

2024-02-13 21:44 UTC, dbasunag commented
/wip cancel

2024-02-14 13:11 UTC, dbasunag commented on pyproject.toml
> +version = "0.0.1"
Should this be left as it was?

2024-02-14 13:20 UTC, myakove requested changes

2024-02-14 13:20 UTC, myakove commented on tests/polarion/test_polarion.py
> +def test_polarion_requirement_no_args():
missing tests to test the code itself

2024-02-14 13:20 UTC, myakove commented on pyproject.toml
> +pyappsutils-polarion_tc_requirements = "apps.polarion.polarion_verify_tc_requirements:has_verify"
replace `_` with `-`

2024-02-14 13:20 UTC, myakove commented on apps/polarion/polarion_verify_tc_requirements.py
> +LOGGER = logging.getLogger(__name__)
use `python-simple-logger`

2024-02-14 13:32 UTC, rnetser requested changes

2024-02-14 13:32 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +    if tests_with_missing_requirements:
```suggestion
    if tests_with_missing_requirements := validate_polarion_requirements(...):
```

2024-02-14 13:32 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +        missing_str = "\n".join(tests_with_missing_requirements)
used once

2024-02-14 13:32 UTC, rnetser commented on apps/polarion/polarion_utils.py
> +    removed_ids = find_polarion_ids(data=diff.get("removed", []), polarion_project_id=polarion_project_id)
not used, please remove

2024-02-14 13:32 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +    git_diff = git_diff_added_removed_lines()
used once

2024-02-14 13:32 UTC, rnetser commented on apps/polarion/README.md
> +This script uses [pylero](https://github.com/RedHatQE/pylero) and expects .pylero config file to be present in current directory or user's home directory.
missing from pyproject

2024-02-14 15:50 UTC, dbasunag commented on apps/polarion/README.md
> +This script uses [pylero](https://github.com/RedHatQE/pylero) and expects .pylero config file to be present in current directory or user's home directory.
It is under [tool.poetry.dependencies], got added accidentally in the first PR.

2024-02-14 15:50 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +    removed_ids = find_polarion_ids(data=diff.get("removed", []), polarion_project_id=polarion_project_id)
It will be used in the next PR. Do you want me to remove it now and add it back with the next PR?

2024-02-14 15:51 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +    git_diff = git_diff_added_removed_lines()
This is to keep the code cleaner and will also be used in my next PR.

2024-02-14 18:27 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +    removed_ids = find_polarion_ids(data=diff.get("removed", []), polarion_project_id=polarion_project_id)
Done.

2024-02-14 19:10 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +def test_polarion_requirement_no_args():
Not resolving this one, till I discuss it with you.

2024-02-15 18:47 UTC, dbasunag commented on pyproject.toml
> +version = "0.0.1"
Leaving it 0.0.0

2024-02-15 18:47 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +def test_polarion_requirement_no_args():
Added two tests.

2024-02-15 18:47 UTC, dbasunag commented on pyproject.toml
> +pyappsutils-polarion_tc_requirements = "apps.polarion.polarion_verify_tc_requirements:has_verify"
Done.

2024-02-15 18:47 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +LOGGER = logging.getLogger(__name__)
Done

2024-02-15 18:48 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +        missing_str = "\n".join(tests_with_missing_requirements)
Changed this one.

2024-02-15 18:48 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +    git_diff = git_diff_added_removed_lines()
Moved to where it is needed.

2024-02-28 11:40 UTC, myakove requested changes

2024-02-28 11:40 UTC, myakove commented on tests/polarion/test_polarion.py
> +from simple_logger.logger import get_logger
please add pytest-cov
check https://github.com/RedHatQE/ci-jobs-trigger

2024-02-28 11:40 UTC, myakove commented on tox.ini
> +    poetry run pytest tests/polarion/test_polarion.py -svvv
why `svvv`? no need to `v` here

2024-02-28 11:51 UTC, rnetser requested changes

2024-02-28 11:51 UTC, rnetser commented on apps/polarion/README.md
> +## pyappsutils-polarion_tc_requirements
why mix of hyphen and underscores?

2024-02-28 11:51 UTC, rnetser commented on apps/polarion/polarion_utils.py
> +        match = re.findall(rf"pytest.mark.polarion.*{polarion_project_id}-[0-9]+", item)
can be unified with the next seach; use grouping to extract what is needed

2024-02-28 11:51 UTC, rnetser commented on apps/polarion/polarion_utils.py
> +def get_polarion_ids_from_diff(diff, polarion_project_id):
this is used once and is a wrapper to another function; call directly where needed

2024-02-28 11:51 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +    LOGGER.info(f"Checking following ids: {added_ids}")
should be under the if

2024-02-28 11:51 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +    added_ids = get_polarion_ids_from_diff(diff=git_diff_lines(), polarion_project_id=polarion_project_id)
use wolrus

2024-02-28 11:51 UTC, rnetser commented on apps/utils.py
> +
the 2 can be united into 1 function

2024-02-28 11:51 UTC, rnetser commented on pyproject.toml
> +pyappsutils-polarion-tc-requirements = "apps.polarion.polarion_verify_tc_requirements:has_verify"
```suggestion
pyappsutils-polarion-verify-tc-requirements = "apps.polarion.polarion_verify_tc_requirements:has_verify"
```

the command needs to indicate that this is about verifying 

also, please shorten `pyappsutils` to something like `pyutils`

2024-02-28 12:04 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +            diff.setdefault("removed", []).append(line)
Was going to be used in next PR, but removed it.

2024-02-28 12:04 UTC, dbasunag commented on apps/polarion/README.md
> +## pyappsutils-polarion_tc_requirements
updated

2024-02-28 12:04 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +        match = re.findall(rf"pytest.mark.polarion.*{polarion_project_id}-[0-9]+", item)
Committed your suggestion

2024-02-28 12:05 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +def get_polarion_ids_from_diff(diff, polarion_project_id):
This would be again used in the next PR for approving polarion, best to keep it a separate function.

2024-02-28 12:35 UTC, dbasunag commented on pyproject.toml
> +pyappsutils-polarion-tc-requirements = "apps.polarion.polarion_verify_tc_requirements:has_verify"
This was named based on review comments. Now it is being used in cnv-tests. I would prefer to keep it as `pyappsutils`.

2024-02-28 12:36 UTC, dbasunag commented on pyproject.toml
> +pyappsutils-polarion-tc-requirements = "apps.polarion.polarion_verify_tc_requirements:has_verify"
added `verify`.

2024-02-28 12:38 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +def get_polarion_ids_from_diff(diff, polarion_project_id):
Nevermind. You are right. Will remove.

2024-02-28 12:40 UTC, dbasunag commented on apps/utils.py
> +
Done

2024-02-28 12:45 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +from simple_logger.logger import get_logger
Ok, adding it under tool.poetry.group.tests.dependencies

2024-02-28 13:40 UTC, dbasunag commented on pyproject.toml
> +pyappsutils-polarion-tc-requirements = "apps.polarion.polarion_verify_tc_requirements:has_verify"
I will just shorten it as you adviced. I agree it is annoying to have a long name.

2024-02-29 08:00 UTC, myakove commented on apps/utils.py
> +            config_yaml = yaml.safe_load(_file)
```suggestion
            return yaml.safe_load(_file).get(util_name, {})
```

2024-02-29 08:01 UTC, myakove commented on apps/utils.py
> +    return config_yaml.get(util_name, {})
```suggestion
    return {}
```

2024-02-29 14:20 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +        if match := re.findall(rf"pytest.mark.polarion.*{polarion_project_id}-[0-9]+", item):
This is from @rnetser 's commit.

2024-02-29 16:12 UTC, dbasunag commented on apps/polarion/README.md
> +pyutils-polarion-tc-requirements --project_id <project_id>
Done.

2024-02-29 16:12 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +        LOGGER.info(line)
Done.

2024-02-29 16:13 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +        if match := re.findall(rf"pytest.mark.polarion.*{polarion_project_id}-[0-9]+", item):
Ok, I see what you mean. I originally thought @rnetser was only talking about the line for which she provided suggested update. I will see how to address this one.

2024-02-29 18:34 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +        if match := re.findall(rf"pytest.mark.polarion.*{polarion_project_id}-[0-9]+", item):
I have made more changes as it does not make sense to use re.findall() on each lines,instead, I will combine all the data and use re.findall() on the entire added lines, to extract all the matches. Since findall returns list of matches, I would need to run another findall() to extract just the ids from these matches.

2024-02-29 19:06 UTC, dbasunag commented on pyproject.toml
> +pytest-cov = "^4.1.0"
Updated/Added as adviced.

2024-02-29 19:14 UTC, dbasunag commented
/verified

2024-02-29 20:35 UTC, myakove commented on pyproject.toml
> +directory = ".tests_coverage"
you add the wrong dir in .gitignore.

2024-02-29 20:36 UTC, myakove commented on tox.ini
> +    poetry run pytest tests/ -svv
why -svv?

2024-02-29 20:38 UTC, myakove commented on apps/polarion/polarion_utils.py
> +        LOGGER.info(f"Checking if {_id} verifies any requirement")
do not log anything beside the final output.
enable debug to get more logs

2024-02-29 22:08 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +        click.echo("Polarion project id must be passed via config file or command line")
I would need to parse the output for test_polarion_with_no_requirement, works with click.echo()

2024-02-29 22:09 UTC, dbasunag commented on tox.ini
> +    poetry run pytest tests/ -svv
I just like seeing the output for sanity.

2024-02-29 22:10 UTC, dbasunag commented on pyproject.toml
> +directory = ".tests_coverage"
Will change.

2024-02-29 22:29 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +    return list(set(re.findall(rf"{polarion_project_id}-[0-9]+", "\n".join(matches)))) if matches else []
`re.findall(rf"pytest.mark.polarion.*({polarion_project_id}-[0-9]+)+", "\n".join(data), re.MULTILINE | re.IGNORECASE)` worked

2024-02-29 22:41 UTC, dbasunag commented on tox.ini
> +    poetry run pytest tests/ -svv
Removed verbose option :(

2024-02-29 22:41 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +        LOGGER.info(f"Checking if {_id} verifies any requirement")
Done

2024-02-29 22:50 UTC, dbasunag commented
/verified

2024-03-03 09:43 UTC, rnetser requested changes

2024-03-03 09:43 UTC, rnetser commented on tests/utils.py
> +    return CliRunner()
why is this function needed? it a wrapper to instantiate `CliRunner`

2024-03-03 09:43 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +    if tests_with_missing_requirements:
this is not resolved

2024-03-03 09:43 UTC, rnetser commented on tests/polarion/test_polarion.py
> +    assert "Polarion project id must be passed via config file or command line" in result.output
why are you testing the logs?

2024-03-03 09:43 UTC, rnetser commented on tests/polarion/test_polarion.py
> +    assert result.exit_code == 1
please add assert message

2024-03-03 09:43 UTC, rnetser commented on tests/polarion/test_polarion.py
> +    LOGGER.info(f"Result output: {result.output}, exit code: {result.exit_code}, exceptions: {result.exception}")
why is this log needed? remove or set to debug
if the test fails, add the relevant info.

2024-03-03 09:43 UTC, rnetser commented on tests/polarion/test_polarion.py
> +    assert result.exit_code == 0
please add assert message

2024-03-03 09:43 UTC, rnetser commented on tests/polarion/test_polarion.py
> +            assert f"TestCases with missing requirement: {validate_req.return_value}" in result.output
why test the log?

2024-03-04 17:37 UTC, dbasunag commented on tests/utils.py
> +    return CliRunner()
This was based on review comment https://github.com/RedHatQE/python-utility-scripts/pull/4/files/b6ff90fa675321afc343bb01f076a53459feada4#r1479707480

2024-03-04 17:41 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +    if tests_with_missing_requirements:
I missed it. Will address.

2024-03-04 17:42 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +    assert "Polarion project id must be passed via config file or command line" in result.output
To see we are raising expected error messages and the failure is not due to something unrelated.

2024-03-04 17:46 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +    assert result.exit_code == 1
In some tests the messages are useless, e.g. test_polarion_requirement(), I will update to add messages for tests where it would make sense.

2024-03-04 17:46 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +    LOGGER.info(f"Result output: {result.output}, exit code: {result.exit_code}, exceptions: {result.exception}")
Changing to debug.

2024-03-04 17:47 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +    assert result.exit_code == 0
Here it would not add any value to have an assert message. Leaving it as it is.

2024-03-13 13:25 UTC, dbasunag commented
/verified

2024-03-14 12:56 UTC, myakove requested changes

2024-03-14 12:56 UTC, myakove commented on apps/polarion/polarion_utils.py
> +def git_diff():
we should use https://gitpython.readthedocs.io/en/stable/quickstart.html#diffs

2024-03-14 12:56 UTC, myakove commented on apps/polarion/polarion_utils.py
> +        LOGGER.debug(f"Checking if {_id} verifies any requirement")
How the user set the logger level?

2024-03-14 12:56 UTC, myakove commented on apps/polarion/polarion_utils.py
> +def find_polarion_ids(polarion_project_id, data):
Used once, not need to have function for this, use when it is neeed.

2024-03-14 13:25 UTC, rnetser requested changes

2024-03-14 13:25 UTC, rnetser commented on apps/polarion/polarion_verify_tc_requirements.py
> +        click.echo("Polarion project id must be passed via config file or command line")
please extract to aa separate function

2024-03-14 13:25 UTC, rnetser commented on tests/polarion/test_polarion.py
> +            "added": ['+ @pytest.mark.polarion("ABC-1212")', '+ @pytest.mark.polarion("ABC-1213")']
why is this needed if return value f `validate_polarion_requirements` is overwritten?

2024-03-14 13:25 UTC, rnetser commented on tests/polarion/test_polarion.py
> +            assert result.exit_code == 1, ERROR_MESSAGE.format(exit_code=result.exit_code)
```suggestion
            assert result.exit_code != 0, ERROR_MESSAGE.format(exit_code=result.exit_code)
```

2024-03-18 00:14 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +def find_polarion_ids(polarion_project_id, data):
This would be used in my future PR as well. I would need utility to approve polarion ids, where this is going to be reused.

2024-03-18 00:16 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +            "added": ['+ @pytest.mark.polarion("ABC-1212")', '+ @pytest.mark.polarion("ABC-1213")']
unittest mock did not work without mocking all the functions.

2024-03-18 00:19 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +        click.echo("Polarion project id must be passed via config file or command line")
Since it would only be used once, based on @myakove 's above comment, I will add it when I need to add it in the next PR.

2024-03-18 00:42 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +        LOGGER.debug(f"Checking if {_id} verifies any requirement")
I am adding verbosity

2024-03-18 01:57 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +def git_diff():
It is not that straight forward to get the diffs using git python. I will explore it further in future, but for the time being proceeding with the current code.

2024-03-19 07:14 UTC, myakove requested changes

2024-03-19 07:14 UTC, myakove commented on apps/polarion/polarion_utils.py
> +def git_diff():
I think since it's new code we should push it as it should be and not wait for later.

```
In [49]: from git import Repo

In [50]: repo = Repo.init(".")

In [51]: prev_commits = list(repo.iter_commits(max_count=10))

In [55]: tree = prev_commits[-1].tree

In [56]: _diff = repo.index.diff(tree)

In [58]: [i.a_path for i in  repo.index.diff(tree)]
Out[58]:
['.pre-commit-config.yaml',
 'openshift_cli_installer/cli.py',
 'openshift_cli_installer/libs/clusters/ipi_cluster.py',
 'openshift_cli_installer/libs/clusters/ocm_cluster.py',
 'openshift_cli_installer/libs/clusters/ocp_cluster.py',
 'openshift_cli_installer/libs/clusters/ocp_clusters.py',
 'openshift_cli_installer/libs/clusters/osd_cluster.py',
 'openshift_cli_installer/libs/clusters/rosa_cluster.py',
 'openshift_cli_installer/utils/clusters.py',
 'poetry.lock']

In [59]: [i.change_type for i in  repo.index.diff(tree)]
Out[59]: ['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M']
```

2024-03-19 07:14 UTC, myakove commented on apps/polarion/polarion_verify_tc_requirements.py
> +        click.echo("Polarion project id must be passed via config file or command line")
I don;t understand your answer.

Also please do not resolve while we both not agreed on the answer/changed code.

2024-03-19 07:14 UTC, myakove commented on tests/polarion/test_polarion.py
> +            "added": ['+ @pytest.mark.polarion("ABC-1212")', '+ @pytest.mark.polarion("ABC-1213")']
`validate_polarion_requirements` you shouldn't mock your own functions, this miss the purpose of the testing.

2024-03-19 15:16 UTC, dbasunag commented on apps/polarion/README.md
> +This script uses [pylero](https://github.com/RedHatQE/pylero) and expects .pylero config file to be present in current directory or user's home directory.
Ok, Added Requirements header and moved Usage down.

2024-03-19 15:23 UTC, dbasunag commented on apps/polarion/polarion_utils.py
> +def git_diff():
I need the content of the files with clear information on what was added and removed to extract the polarion ids. Leaving it as it is based on chat.

2024-03-19 16:25 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +            "added": ['+ @pytest.mark.polarion("ABC-1212")', '+ @pytest.mark.polarion("ABC-1213")']
Multiple mocking is needed, when you have multiple function calls that impact the flow. validate_polarion_requirements() call would only be reached based on behavior of the call git_diff_lines() - which now has been removed. Now I have to mock that re.findall call, so that I can reach the validate_polarion_requirements() call to test it.

2024-03-22 13:44 UTC, dbasunag commented
/verified

2024-03-24 08:22 UTC, myakove requested changes

2024-03-24 08:22 UTC, myakove commented on apps/unused_code/unused_code.py
> +        LOGGER.debug(f"Following functions are getting skipped: {ignore_function_lists}")
How the user set the log level?

2024-03-24 08:22 UTC, myakove commented on tests/polarion/test_polarion.py
> +ERROR_MESSAGE = "{exit_code} does not match expected value."
EXIT_CODE_ERROR_MESSAGE

2024-03-24 08:22 UTC, myakove commented on tests/polarion/test_polarion.py
> +        with mock.patch("apps.polarion.polarion_verify_tc_requirements.validate_polarion_requirements") as validate_req:
you mock your own function `validate_polarion_requirements`

2024-03-25 17:46 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +        with mock.patch("apps.polarion.polarion_verify_tc_requirements.validate_polarion_requirements") as validate_req:
Right, but the line to mock validate_polarion_requirements won't be reached if I don't mock re. findall call.

2024-03-25 22:58 UTC, dbasunag commented on apps/unused_code/unused_code.py
> +        LOGGER.debug(f"Following functions are getting skipped: {ignore_function_lists}")
Added verbosity option.

2024-03-25 22:58 UTC, dbasunag commented on tests/polarion/test_polarion.py
> +ERROR_MESSAGE = "{exit_code} does not match expected value."
Renamed.

2024-03-30 19:40 UTC, myakove requested changes

2024-03-30 19:40 UTC, myakove commented on apps/polarion/polarion_verify_tc_requirements.py
> +        click.echo("Polarion project id must be passed via config file or command line")
Use `run_command` and logger instead `click.echo` 
check https://github.com/RedHatQE/openshift-cli-installer/blob/main/openshift_cli_installer/tests/test_user_input.py

2024-04-01 15:44 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +        click.echo("Polarion project id must be passed via config file or command line")
I would prefer to not to use openshift-python-utilities. It uses wrapper and I need to be able to use this repository to all cnv-tests and openshift-virtualization-tests repo branches, without needing to worry about the wrapper version pinned. click is already being used, so using clock.echo is simpler.

2024-04-03 19:10 UTC, dbasunag commented on apps/polarion/polarion_verify_tc_requirements.py
> +        click.echo("Polarion project id must be passed via config file or command line")
It does not seem possible with mocking. Because the function in the standalone script is not getting mocked and if I use cliRunner() then the same problem comes back - I can't access the error messages, unless I use click.echo().

2024-04-04 10:45 UTC, myakove commented
/verified

2024-04-04 10:57 UTC, myakove approved these changes

2024-04-04 10:58 UTC, merged