jira initial pr
RedHatQE/python-utility-scripts pull request #62
Opened 2024-05-30 22:05 UTC by dbasunag

2024-05-30 22:05 UTC, redhat-qe-bot1 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-05-30 22:12 UTC, dbasunag commented
/wip

2024-08-22 08:00 UTC, myakove requested changes

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +def get_jira_mismatch(jira_cfg_file: Any, jira_target_versions: Any, verbose: bool) -> Any:
you use typing but set everything to `Any`, it's the same as not using typing.

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    if not (config_dict.get("url") and config_dict.get("token")):
`(config_dict.get("url") and config_dict.get("token")`  save both and reuse them

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    resolved_status = config_dict.get("resolved_statuses") or DEFAULT_RESOLVED_STATUS
```suggestion
    resolved_status = config_dict.get("resolved_statuses", DEFAULT_RESOLVED_STATUS) 
```

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    jira_error: Dict[str, Any] = {"status_mismatch": {}, "version_mismatch": {}, "connection_error": {}}
```suggestion
    jira_error: Dict[str, Dict[str, Any]] = {"status_mismatch": {}, "version_mismatch": {}, "connection_error": {}}
```

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +    issue_pattern = r"([A-Z]+-[0-9]+)"
Should be configurable via config file

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +    _is_jira_open = re.findall(rf"jira_id\s*=[\s*\"\']*{issue_pattern}.*", file_content)
`_is_jira_open` please rename to a more logic name.

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +    _jira_url_jiras = []
why do you need to set it here as empty list?

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +    jira_found = {}
missing typing

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +                if "<skip-jira_utils-check>" not in line:
please reverse the login, 
if "<skip-jira_utils-check>" in line:
    continue

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +        with open(filename) as fd:
you should run on all the file, not on every line
` re.findall(rf"pytest.mark.jira.*?([A-Z]+-[0-9]+.*|[<.*>])",`

```
['CNV-111)',
 'CNV-222)  <skip-jira_utils-check>',
 'CNV-333) <skip-jira_utils-check>']
```

then filter the ones with <skip> and return unique list

2024-08-22 08:00 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    jira_error = {key: value for key, value in jira_error.items() if value}
I don;t understand this line

2024-08-22 16:05 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +        with open(filename) as fd:
Thank you! Will update.

2024-08-22 16:06 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +    issue_pattern = r"([A-Z]+-[0-9]+)"
But jira tickets are always this pattern, no?

2024-08-23 09:35 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +    issue_pattern = r"([A-Z]+-[0-9]+)"
I don;t know, this is the case in our Jira but other may be set different

2024-08-23 15:13 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +def get_jira_mismatch(jira_cfg_file: Any, jira_target_versions: Any, verbose: bool) -> Any:
Will fix.

2024-08-23 15:15 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    jira_error = {key: value for key, value in jira_error.items() if value}
This line is not needed.

2024-08-23 15:21 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +    _jira_url_jiras = []
removed

2024-08-23 15:28 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +        with open(filename) as fd:
I remember why I implemented it in this way. Jira ids can be of different format.
e.g. pytest.mark.jira(<>), jira_id=<>, and the entire url). I want to support skipping for all 3. So, either I need to have 3 separate pattern matches on the entire files to capture all the 3 patterns or I can first filter out the skips and then look for the unique ones. I thought the second one is less expensive. Please let me know what you think.

2024-08-23 20:14 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +                if "<skip-jira_utils-check>" not in line:
Done

2024-08-23 20:14 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +    jira_found = {}
Done.

2024-08-23 20:14 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +    _is_jira_open = re.findall(rf"jira_id\s*=[\s*\"\']*{issue_pattern}.*", file_content)
Renamed.

2024-08-26 08:03 UTC, myakove requested changes

2024-08-26 08:03 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +    LOGGER.info(f"Following jiras are found: {jira_found}")
LOGGER should be under `if jira_found`

2024-08-26 08:03 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +        with open(filename) as fd:
ok

2024-08-26 08:03 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +            for line in fd.readlines():
`line for line in fd.readlines() if "<skip-jira-utils-check>" not in line`

2024-08-26 08:45 UTC, rnetser requested changes

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/README.md
> +pyutils-unusedcode --jira-target-versions '1.0.0,2.0.1'
```suggestion
pyutils-jira --jira-target-versions '1.0.0,2.0.1'
```

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/README.md
> + #https://issues.redhat.com/browse/OSD-5716 <skip-jira_utils-check>
the example needs to be updated to a command

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/get_jira_information.py
> +DEFAULT_RESOLVED_STATUS = ["verified", "release pending", "closed", "resolved"]
should be added to the readme, if `resolved_statuses` is not provided, the default resolved ....

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/README.md
> +`~/.config/python-utility-scripts/jira_utils/config.cfg`
this is the default; can be overwritten using click. please add a comment about it

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/get_jira_information.py
> +    type=click.Path(),
```suggestion
    type=click.Path(exists=True),
```

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/get_jira_information.py
> +    if not (jira_url and jira_token and jira_issue_pattern):
`jira_issue_pattern` has default so the condition here for it will never be False

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/get_jira_information.py
> +                # check closed status:
```suggestion
                # check resolved status:
```

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/get_jira_information.py
> +                    current_target_version = fix_version.group(1) if fix_version else "vfuture"
isn't `vfuture` very project-specific? should it be set in the config?

2024-08-26 08:45 UTC, rnetser commented on apps/jira_utils/exceptions.py
> +class JiraInvalidConfigFileError(Exception):
can be under jira_utils

2024-08-26 08:45 UTC, rnetser commented on example.jira.yaml
> +pyutils-jira:
we have `config.example.yaml` and `example.jira.yaml` - we should remove this duplication.

2024-08-26 19:18 UTC, dbasunag commented on apps/jira_utils/exceptions.py
> +class JiraInvalidConfigFileError(Exception):
Sure.

2024-08-26 19:23 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +        LOGGER.info(f"Retry staistics: {self.get_issue.statistics}")
It shows the retry stats. In case jira is slow or there is an outage/some issues were not accessible, it could be helpful information

2024-08-27 23:31 UTC, dbasunag commented on apps/jira_utils/README.md
> + #https://issues.redhat.com/browse/OSD-5716 <skip-jira_utils-check>
This one is an example on how to utilize the skip. This is not associated with a command.

2024-08-27 23:54 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +                    current_target_version = fix_version.group(1) if fix_version else "vfuture"
I would still need to pass a default value though.

2024-08-28 00:05 UTC, dbasunag commented on apps/jira_utils/jira_utils.py
> +class JiraConnector:
Removed.

2024-08-28 00:08 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    jira_error = {key: value for key, value in jira_error.items() if value}
If there is no error, jira_error dict would still be  {'status_mismatch': {}, 'version_mismatch': {}, 'connection_error': {}}, jira_error.values() would be still a list of empty dicts, no? to avoid that I need to filter out the keys, which are associated with empty dicts.

2024-08-28 00:11 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    jira_error = {key: value for key, value in jira_error.items() if value}
I changed the line 56 and would be using set defaults, to avoid having to filter the dict.

2024-09-02 07:19 UTC, myakove requested changes

2024-09-02 07:19 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    jira_issue_pattern = config_dict.get("issue_pattern", jira_issue_pattern)
Here we prefer values from config over cli, We should get the cli value if passed

2024-09-02 07:19 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    jira_url = config_dict.get("url")
url and token should also be expose in the CLI and via os environment.

2024-09-02 07:19 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +@click.option(
everything that in the config should be also exposed in the CLI

2024-09-02 07:19 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    for file_name in (jira_id_dict := get_jiras_from_python_files(issue_pattern=jira_issue_pattern, jira_url=jira_url)):
`get_jiras_from_python_files` return dict, you should run on key, val

2024-09-02 07:19 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +                jira_issue_metadata = get_issue(jira=jira_connection, jira_id=jira_id).fields
should be run in threads to save time.

2024-09-03 12:26 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    jira_url = config_dict.get("url")
For url - I agree. But I don't like the idea of passing token via cli. How about just OS env for token?

2024-09-03 12:32 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +                jira_issue_metadata = get_issue(jira=jira_connection, jira_id=jira_id).fields
But may be I should ensure that I am not making duplicate call for the same jira.

2024-09-06 12:12 UTC, myakove requested changes

2024-09-06 12:12 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +            for future in concurrent.futures.as_completed(future_to_jiras):
Should be outside the `with` block

2024-09-06 12:12 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    if jira_id_dict := get_jiras_from_python_files(issue_pattern=jira_issue_pattern, jira_url=jira_url):
`jira_id_dict` already contain the file name, you should pass to `get_jira_information` and `get_jira_information` can return it, this will make the for loop over all files obsolete

2024-09-06 12:12 UTC, myakove commented on apps/jira_utils/jira_utils.py
> +class JiraInvalidConfigFileError(Exception):
Please move the classes to the top.

2024-09-06 12:12 UTC, myakove commented on apps/jira_utils/README.md
> +```bash
This is not `bash`

2024-09-06 12:12 UTC, myakove commented on apps/jira_utils/README.md
> +```bash
ditto

2024-09-06 12:12 UTC, myakove commented on tests/jira_utils/test_jira.py
> +def test_jira_missing_config_file():
We need more tests

2024-09-06 13:53 UTC, dbasunag commented on tests/jira_utils/test_jira.py
> +def test_jira_missing_config_file():
Without exposing the tokens/urls, it would be hard to add more tests outside of field validations. If you have any suggestions, please do let me know.

2024-09-06 13:56 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    config_dict = get_util_config(util_name="pyutils-jira", config_file_path=jira_cfg_file)
I might be missing what you are saying, If I add a function to get the field, that won't change the number of lines of code. Since the call would still be needed. Can you please elaborate?

2024-09-06 13:59 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +            for future in concurrent.futures.as_completed(future_to_jiras):
https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor-example Went with this example. It shows the for loop inside the with block.

2024-09-06 14:04 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
```
Changed in version 3.5: If max_workers is None or not given, it will default to the number of processors on the machine, multiplied by 5, assuming that [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) is often used to overlap I/O instead of CPU work and the number of workers should be higher than the number of workers for [ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor).
```
https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor - May be I should set it to `None` instead?

2024-09-06 14:08 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    if jira_id_dict := get_jiras_from_python_files(issue_pattern=jira_issue_pattern, jira_url=jira_url):
I am not getting fully what you are saying here. My motivation here was to use thread effectively and not make duplicate calls for the same jiras. Let me try based on my interpretation, and next review can tell me if my assumption is aligned to what you are expecting.

2024-09-06 14:10 UTC, dbasunag commented on apps/jira_utils/README.md
> +```bash
Changed to text

2024-09-06 14:12 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    config_dict = get_util_config(util_name="pyutils-jira", config_file_path=jira_cfg_file)
May be you want a function to process all inputs and return them all?

2024-09-06 14:49 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    if jira_id_dict := get_jiras_from_python_files(issue_pattern=jira_issue_pattern, jira_url=jira_url):
I gave it a try, but it would be inefficient to have to get the file names in get_jira_information(). The reason being, the same jira can be associated with multiple files. In the with block I am only creating threads for the unique jiras, if inside get_jira_information() now I have to loop through jira_id_dict, to get the relevant files, instead of 1 for loop at the end like I am doing, I would be having n for loops, once for each unique jiras.

2024-09-11 09:24 UTC, myakove requested changes
Partial review

2024-09-11 09:24 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +) -> None:
When running without args we get nasty exception, check if required args not passed and show proper error message before exit.

2024-09-11 09:24 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +        raise JiraValidationError(error)
Why do you need to raise here?

2024-09-11 09:24 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +    LOGGER.info("Successfully completed Jira validations")
Seems redundant, please remove

2024-09-11 09:24 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +                    jira_error[jira_id] = f" {file_names}: {jira_error_string}"
The output should be:
<file name>: list of Jira issues

2024-09-11 09:27 UTC, myakove commented
@dbasunag 
please rename the file `get_jira_information.py`

2024-09-11 16:13 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    "--cfg-file",
You are right. It should be changed to  `config-file-path` to match with the other scripts.

2024-09-11 16:14 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +) -> None:
You already addressed it. Thank you!

2024-09-11 16:18 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +        raise JiraValidationError(error)
I want to convey if the validation failed or passed. In the previous PRs (polarions), the reviews recommended raising specific exceptions instead of click.Abort(). What do you suggest?

2024-09-11 16:19 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +    LOGGER.info("Successfully completed Jira validations")
This was addressed by you. Resolving.

2024-09-11 16:19 UTC, dbasunag commented on apps/jira_utils/get_jira_information.py
> +                    jira_error[jira_id] = f" {file_names}: {jira_error_string}"
Addressed by you. Resolving.

2024-09-15 05:33 UTC, rnetser commented on apps/jira_utils/jira_information.py
> +        sys.exit(1)
consider using https://github.com/janLuke/cloup for this; it is clearer to see the logic when options and conditions are set next to each other.

2024-09-15 05:33 UTC, rnetser commented on tests/jira_utils/test_jira.py
> +def test_jira_missing_config_file():
mock jira

2024-09-16 05:55 UTC, myakove commented on apps/jira_utils/get_jira_information.py
> +        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
Yes

2024-09-16 11:34 UTC, dbasunag commented on apps/jira_utils/jira_information.py
> +        sys.exit(1)
@rnetser, @myakove suggested sys.exit(), I will check with him and explore this one.

2024-09-16 11:36 UTC, dbasunag commented on tests/jira_utils/test_jira.py
> +def test_jira_missing_config_file():
I can't mock jira with run_command. I was asked to use run_command instead of CliRunner().

2024-09-17 06:57 UTC, rnetser commented on tests/jira_utils/test_jira.py
> +def test_jira_missing_config_file():
iiuc correctly, the comment was to add more tests to check the code functionality (i.e the functions), @myakove is this what you meant?

2024-09-17 14:41 UTC, dbasunag commented on tests/jira_utils/test_jira.py
> +def test_jira_missing_config_file():
@rnetser I spoke with @myakove on this one. His earlier comment was about polarion tests, and I misunderstood and took it as for everything. Based on my conversation with Meni, I will remove all tests from this PR and create a separate PR with mocking jira.

2024-09-17 17:26 UTC, dbasunag commented on apps/jira_utils/jira_information.py
> +        sys.exit(1)
@rnetser I took a look at the library you suggested. It is pretty neat. But with just one validation here, it does not seem the benefit would be significant. But I want to use it at some point somewhere. Thank you for sharing!

2024-09-29 08:45 UTC, myakove requested changes

2024-09-29 08:45 UTC, myakove commented on apps/jira_utils/jira_information.py
> +    Try to find all Jira tickets in a given file content.
empty line after first line in docstring.

2024-09-29 08:45 UTC, myakove commented on apps/jira_utils/jira_information.py
> +        unique_jiras = set()
why do you need to set this here? I think you can remove it.

2024-09-29 08:45 UTC, myakove commented on apps/jira_utils/jira_information.py
> +                file_content="\n".join([line for line in fd.readlines() if "<skip-jira-utils-check>" not in line]),
save `fd.readlines()` and call `get_jira_ids_from_file_content` outside of the `with open` block.
No need to have the file open during the process.

2024-09-29 08:45 UTC, myakove commented on apps/jira_utils/jira_information.py
> +        LOGGER.error("Jira config file must contain valid url or token.")
this log is misleading, url, token can be provided via cli as well

2024-09-29 08:45 UTC, myakove commented on apps/utils.py
> +    if config_file_path and os.path.exists(config_file_path):
if `config_file_path` is not mandatory please set it as optional in the function

2024-10-01 06:57 UTC, myakove submitted a review, later dismissed

2024-10-01 20:11 UTC, dbasunag commented
/retest python-module-install

2024-10-02 08:17 UTC, myakove requested changes

2024-10-02 08:17 UTC, myakove commented on apps/jira_utils/jira_information.py
> +        LOGGER.error("Jira config file must contain valid url or token.")
Please change the log to reflect the real issue.

2024-10-02 11:24 UTC, dbasunag commented
@myakove https://github.com/RedHatQE/python-utility-scripts/pull/62#discussion_r1784014584 was already addressed.

2024-10-02 11:25 UTC, dbasunag commented on apps/jira_utils/jira_information.py
> +        LOGGER.error("Jira config file must contain valid url or token.")
It currently shows `"Jira url and token are required."`

2024-10-02 12:29 UTC, myakove approved these changes

2024-10-02 16:30 UTC, dbasunag commented
/verified

2024-10-02 16:43 UTC, merged